<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAcflrSx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAcflrSx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAcflrSx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAcflrSx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAcflrSx\App_KernelDevDebugContainer([
    'container.build_hash' => 'AcflrSx',
    'container.build_id' => '7439ea8a',
    'container.build_time' => 1645781212,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAcflrSx');
